### ISSUE TITLE
CUDA not connecting when running main.py

### ISSUE THREAD

**Issue by DefZee** [maximedrn/opensea-automatic-bulk-upload-and-sale#211]
Firstly, wanted to say you're an absolute star for working on this project - you're a sanity saviour (from mass manual uploads).
I have one issue I wanted to raise: when running the script, it seems to say my graphics card does not have CUDA. 

![20220326_193536](https://user-images.githubusercontent.com/102434650/160254742-03db52b3-7b85-45bc-b83a-3dbd551ae7c2.jpg)

I'm running a 2080ti, have installed CUDA 11.6. Everything checks out, the script works, but the CUDA processing doesn't seem to be integrating. Any advice?
Thanks in advance.

**Comment by maximedrn** [comment]
This screenshot shows that you have installed Torch+CUDA 11.3 (2080ti 12GB should be ultra fast). All is good :)
That error mentioned above is due to some unnecessary files that I deleted (`requirements.txt` file and `.git` clone directory)

You will know if your GPU is running by looking at the task manager, the graphics card will be used at +50% when it solves the reCAPTCHA.

**Comment by DefZee** [comment]
I see, and yeah you'recompletely write about the GPU usage. Thanks for getting back to me.
It's not running super quickly though, and often gets stuck in a captcha cycle. Though I guess that's the limitations of the script, perhaps, on top of Opensea being difficult with all the captchas. 
I found that restarting the script after every 5 uploads or when it gets stuck in an endless cycle of captchas helps kick it back in gear (for anyone that might be having that issue).
Again, thanks a lot for your work! It's fantastic.
