### ISSUE TITLE
Cloudflare protection using a proxy.

### ISSUE THREAD

**Issue by Tastygeek** [maximedrn/opensea-automatic-bulk-upload-and-sale#215]
I don't know if it is because of the use of a proxy, there has been no way to open the opensea website. Is there any other solution?

**Comment by maximedrn** [comment]
If you use a proxy, you may be blocked by OpenSea.

**Comment by jadedtakesthiscereal** [comment]
@Tastygeek I run into this often and my workaround has been, turn off vpn, turn on cloudflare 1.1.1.1, open browser manually, go to opensea let it get past that 5second thing.  then try bot again with in this example cloudflare1.1.1.1 only until it stops me again (usually 100 or so uploads) and then swap back to vpn, open manually get past opensea cloudflare ddos again, and return to uploading.. I sometimes have to swap regions in the vpns to get past it.   Occasionally I use my unhidden connection because worst case my isp reassigns new ip if I unplug modem while I sleep.  Hope that helps some

**Comment by Tastygeek** [comment]
> If you use a proxy, you may be blocked by OpenSea.

I have done more tests, if there is a proxy, you use chrome to visit opensea, you can open it directly. If I use chromedriver, I always stay on the cloudflare 5s page. Combined with the situation that others cannot log in to opensea, can a patch similar to [undetected_chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) be added?

**Comment by Tastygeek** [comment]
> @Tastygeek I run into this often and my workaround has been, turn off vpn, turn on cloudflare 1.1.1.1, open browser manually, go to opensea let it get past that 5second thing. then try bot again with in this example cloudflare1.1.1.1 only until it stops me again (usually 100 or so uploads) and then swap back to vpn, open manually get past opensea cloudflare ddos again, and return to uploading.. I sometimes have to swap regions in the vpns to get past it. Occasionally I use my unhidden connection because worst case my isp reassigns new ip if I unplug modem while I sleep. Hope that helps some

thanks bro, I'll try it

**Comment by maximedrn** [comment]
> > If you use a proxy, you may be blocked by OpenSea.
> 
> I have done more tests, if there is a proxy, you use chrome to visit opensea, you can open it directly. If I use chromedriver, I always stay on the cloudflare 5s page. Combined with the situation that others cannot log in to opensea, can a patch similar to [undetected_chromedriver](https://github.com/ultrafunkamsterdam/undetected-chromedriver) be added?

I already tried this webdriver but Cloudflare detects it. Nothing, to my knowledge, can be done to get past this protection :/
