### ISSUE TITLE
Duplicated text and incorrect NFT name.

### ISSUE THREAD

**Issue by hiqsociety** [maximedrn/opensea-automatic-bulk-upload-and-sale#361]
the uploader has a few issues:
1. the name of the title is sometimes missing. not sure if it's because the uploader missed this or coz the csv file is not aligned properly but since so, the scraper now cannot identify them as... duplicates. i have a collection of 10000, now uploaded all is 10004 and scraper is unable to show any duplicates.

2. sometimes it duplicates the traits naming
e.g. if the trait name is "color", it will duplicate it to "colorcolor" <- i think type syncing is too fast

**Comment by maximedrn** [comment]
It seems to be a problem with Selenium... The bot uses the `send_keys()` method which probably has some problems on the version of Selenium used. Maybe the latest version of Selenium doesn't have this error with duplicate keys. Otherwise for the name, it's impossible, it can't forget the name and send only the numbers.

**Comment by maximedrn** [comment]
I am looking for people who have experienced the same problems.
